build:
    tests:
        override:
            -
                command: python -m unittest discover -s test -p *Test.py

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - test/*

install:
  - pip install etlt
  - pip install pytz

tools:
    pylint:
        python_version: '3'
        config_file: pylintrc